(ns nvidia_cosmos.actor
  "nvidia_cosmos clean-room actor — Clojure over the kotoba Datom log (EAVT, Datomic-isomorphic,
  ADR-2605262130 + ADR-2605312345). World Foundation Models / Physical AI simulation.

  Generated by 70-tools/scaffold_wave11_clj_datomic.py — replaces the Python main.py.
  CRUD + validation over a DI `DatomPort` seam (no external managed DB; the production
  adapter is kotoba-kqe, the test/browser adapter is `in-memory-datom`). No proprietary code."
  (:require [clojure.string :as str]))

;; ── Datomic-style schema (install via -transact) ──────────────────────────
(def schema
  "Attribute installs for this actor's entities (Datomic schema shape)."
  [;; WorldModel
   {:db/ident :nvidia_cosmos.WorldModel/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :nvidia_cosmos.WorldModel/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.WorldModel/modelType :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.WorldModel/parameters :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.WorldModel/checkpoint :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.WorldModel/license :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.WorldModel/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.WorldModel/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Tokenizer
   {:db/ident :nvidia_cosmos.Tokenizer/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :nvidia_cosmos.Tokenizer/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.Tokenizer/kind :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.Tokenizer/compressionRatio :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.Tokenizer/modality :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.Tokenizer/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.Tokenizer/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; SimRun
   {:db/ident :nvidia_cosmos.SimRun/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :nvidia_cosmos.SimRun/worldModelId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.SimRun/prompt :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.SimRun/frames :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.SimRun/status :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.SimRun/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.SimRun/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Embodiment
   {:db/ident :nvidia_cosmos.Embodiment/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :nvidia_cosmos.Embodiment/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.Embodiment/dof :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.Embodiment/robotType :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.Embodiment/urdf :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.Embodiment/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.Embodiment/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Prompt
   {:db/ident :nvidia_cosmos.Prompt/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :nvidia_cosmos.Prompt/text :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.Prompt/modality :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.Prompt/conditioning :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.Prompt/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.Prompt/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; GuardrailCheck
   {:db/ident :nvidia_cosmos.GuardrailCheck/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :nvidia_cosmos.GuardrailCheck/simRunId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.GuardrailCheck/policy :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.GuardrailCheck/verdict :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.GuardrailCheck/score :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.GuardrailCheck/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :nvidia_cosmos.GuardrailCheck/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}])

(def entities #{"WorldModel" "Tokenizer" "SimRun" "Embodiment" "Prompt" "GuardrailCheck"})

;; ── DatomPort — the DI seam to the kotoba Datom log ───────────────────────
(defprotocol DatomPort
  (-transact [this tx-data]
    "Append Datomic-shaped tx-data: entity maps {:db/id … attr v}, [:db/add e a v],
     [:db/retract e a v], [:db/retractEntity e].")
  (-pull [this eid]
    "Return the entity map for eid (incl. :db/id), or nil.")
  (-find-by-attr [this attr]
    "AEVT scan: the eids of every entity carrying attr."))

;; loud-failing default — a forgotten injection must never silently no-op
(defn unwired-datom []
  (reify DatomPort
    (-transact [_ _] (throw (ex-info "nvidia_cosmos: DatomPort not wired — inject kotoba-kqe or in-memory-datom" {:unwired true})))
    (-pull [_ _] (throw (ex-info "nvidia_cosmos: DatomPort not wired" {:unwired true})))
    (-find-by-attr [_ _] (throw (ex-info "nvidia_cosmos: DatomPort not wired" {:unwired true})))))

;; in-memory fake — interprets the Datomic tx-data subset over {eid {attr v}}
(defn in-memory-datom []
  (let [store (atom {})]
    (reify DatomPort
      (-transact [_ tx-data]
        (doseq [op tx-data]
          (cond
            (map? op) (swap! store update (:db/id op) merge (dissoc op :db/id))
            (and (vector? op) (= :db/add (first op)))
            (let [[_ e a v] op] (swap! store assoc-in [e a] v))
            (and (vector? op) (= :db/retract (first op)))
            (let [[_ e a] op] (swap! store update e dissoc a))
            (and (vector? op) (= :db/retractEntity (first op)))
            (let [[_ e] op] (swap! store dissoc e))))
        {:db-after @store})
      (-pull [_ eid] (when-let [m (get @store eid)] (assoc m :db/id eid)))
      (-find-by-attr [_ attr] (vec (for [[eid m] @store :when (contains? m attr)] eid))))))

;; ── coercion (portable) ───────────────────────────────────────────────────
(defn- as-long [v]
  (cond (number? v) #?(:clj (long v) :cljs v)
        (string? v) (try #?(:clj (Long/parseLong (str/trim v))
                            :cljs (let [n (js/parseInt v 10)] (if (js/isNaN n) 0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0))
        :else 0))

(defn- as-double [v]
  (cond (number? v) #?(:clj (double v) :cljs v)
        (string? v) (try #?(:clj (Double/parseDouble (str/trim v))
                            :cljs (let [n (js/parseFloat v)] (if (js/isNaN n) 0.0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0.0))
        :else 0.0))

(defn- as-bool [v]
  (boolean (#{"1" "true" "yes" "on" true} (if (string? v) (str/lower-case v) v))))

(defn- now []
  #?(:clj (str (java.time.Instant/now)) :cljs (.toISOString (js/Date.))))

(defn- new-id [prefix]
  (str prefix "_" (subs (str/replace (str (random-uuid)) "-" "") 0 16)))

(defn- require-fields [data fields]
  (let [missing (remove (fn [k] (some? (get data (keyword k)))) fields)]
    (when (seq missing)
      (throw (ex-info (str "Missing required fields: " (str/join ", " missing))
                      {:type :invalid-request :missing (vec missing)})))))

;; ── list surface: filtering + cursor pagination (L4 parity) ───────────────
(def ^:const default-limit 20)
(def ^:const max-limit 100)

(defn- index-of [v x]
  (loop [i 0] (cond (>= i (count v)) -1 (= (nth v i) x) i :else (recur (inc i)))))

(defn- apply-filters
  "Keep rows matching every {attr v} in flt (string-compared), attr restricted to allowed."
  [rows flt allowed]
  (let [allowed (set allowed)]
    (reduce (fn [rs [a v]]
              (if (and (contains? allowed a) (some? v))
                (filterv (fn [r] (= (str (get r a)) (str v))) rs)
                rs))
            (vec rows) (or flt {}))))

(defn- paginate
  "Cursor pagination over rows → {:object :data :has-more :count :total}.
   opts {:limit N :starting-after <db/id>}."
  [rows opts]
  (let [limit (min (max (or (:limit opts) default-limit) 1) max-limit)
        start (:starting-after opts)
        rows  (vec rows)
        rows  (if start
                (let [idx (index-of (mapv :db/id rows) start)]
                  (if (neg? idx) rows (subvec rows (inc idx))))
                rows)
        page  (vec (take limit rows))]
    {:object "list" :data page :has-more (> (count rows) limit)
     :count (count page) :total (count rows)}))

;; ── WorldModel ────────────────────────────────────────────────────────────────
(defn create-world-model
  "Create a WorldModel."
  [port data]
  (require-fields data ["name" "modelType"])
  (let [id (new-id "cosmos_wor")
        e {:db/id id
           :nvidia_cosmos.WorldModel/id id
           :nvidia_cosmos.WorldModel/name (get data :name)
           :nvidia_cosmos.WorldModel/modelType (get data :modelType)
           :nvidia_cosmos.WorldModel/parameters (as-long (get data :parameters))
           :nvidia_cosmos.WorldModel/checkpoint (get data :checkpoint)
           :nvidia_cosmos.WorldModel/license (get data :license)
           :nvidia_cosmos.WorldModel/createdAt (now)
           :nvidia_cosmos.WorldModel/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-world-models
  "List WorldModel with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-world-models port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :nvidia_cosmos.WorldModel/id))
         rows (apply-filters rows (:filter opts) [:nvidia_cosmos.WorldModel/name :nvidia_cosmos.WorldModel/modelType :nvidia_cosmos.WorldModel/parameters :nvidia_cosmos.WorldModel/checkpoint :nvidia_cosmos.WorldModel/license])]
     (paginate rows opts))))

(defn get-world-model
  "Retrieve a WorldModel by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-world-model port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-world-model
  "Update a WorldModel; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :name) (conj [:db/add id :nvidia_cosmos.WorldModel/name (get data :name)]))
                   (cond-> (contains? data :modelType) (conj [:db/add id :nvidia_cosmos.WorldModel/modelType (get data :modelType)]))
                   (cond-> (contains? data :parameters) (conj [:db/add id :nvidia_cosmos.WorldModel/parameters (as-long (get data :parameters))]))
                   (cond-> (contains? data :checkpoint) (conj [:db/add id :nvidia_cosmos.WorldModel/checkpoint (get data :checkpoint)]))
                   (cond-> (contains? data :license) (conj [:db/add id :nvidia_cosmos.WorldModel/license (get data :license)]))
                   (conj [:db/add id :nvidia_cosmos.WorldModel/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-world-model
  "Delete a WorldModel."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Tokenizer ────────────────────────────────────────────────────────────────
(defn create-tokenizer
  "Create a Tokenizer."
  [port data]
  (require-fields data ["name" "kind"])
  (let [id (new-id "cosmos_tok")
        e {:db/id id
           :nvidia_cosmos.Tokenizer/id id
           :nvidia_cosmos.Tokenizer/name (get data :name)
           :nvidia_cosmos.Tokenizer/kind (get data :kind)
           :nvidia_cosmos.Tokenizer/compressionRatio (as-double (get data :compressionRatio))
           :nvidia_cosmos.Tokenizer/modality (get data :modality)
           :nvidia_cosmos.Tokenizer/createdAt (now)
           :nvidia_cosmos.Tokenizer/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-tokenizers
  "List Tokenizer with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-tokenizers port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :nvidia_cosmos.Tokenizer/id))
         rows (apply-filters rows (:filter opts) [:nvidia_cosmos.Tokenizer/name :nvidia_cosmos.Tokenizer/kind :nvidia_cosmos.Tokenizer/compressionRatio :nvidia_cosmos.Tokenizer/modality])]
     (paginate rows opts))))

(defn get-tokenizer
  "Retrieve a Tokenizer by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-tokenizer port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-tokenizer
  "Update a Tokenizer; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :name) (conj [:db/add id :nvidia_cosmos.Tokenizer/name (get data :name)]))
                   (cond-> (contains? data :kind) (conj [:db/add id :nvidia_cosmos.Tokenizer/kind (get data :kind)]))
                   (cond-> (contains? data :compressionRatio) (conj [:db/add id :nvidia_cosmos.Tokenizer/compressionRatio (as-double (get data :compressionRatio))]))
                   (cond-> (contains? data :modality) (conj [:db/add id :nvidia_cosmos.Tokenizer/modality (get data :modality)]))
                   (conj [:db/add id :nvidia_cosmos.Tokenizer/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-tokenizer
  "Delete a Tokenizer."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── SimRun ────────────────────────────────────────────────────────────────
(defn create-sim-run
  "Create a SimRun."
  [port data]
  (require-fields data ["prompt" "frames"])
  (let [id (new-id "cosmos_sim")
        e {:db/id id
           :nvidia_cosmos.SimRun/id id
           :nvidia_cosmos.SimRun/worldModelId (get data :worldModelId)
           :nvidia_cosmos.SimRun/prompt (get data :prompt)
           :nvidia_cosmos.SimRun/frames (as-long (get data :frames))
           :nvidia_cosmos.SimRun/status (get data :status)
           :nvidia_cosmos.SimRun/createdAt (now)
           :nvidia_cosmos.SimRun/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-sim-runs
  "List SimRun with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-sim-runs port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :nvidia_cosmos.SimRun/id))
         rows (apply-filters rows (:filter opts) [:nvidia_cosmos.SimRun/worldModelId :nvidia_cosmos.SimRun/prompt :nvidia_cosmos.SimRun/frames :nvidia_cosmos.SimRun/status])]
     (paginate rows opts))))

(defn get-sim-run
  "Retrieve a SimRun by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-sim-run port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec
         (and want (contains? want :worldModelId) (get rec :nvidia_cosmos.SimRun/worldModelId))
         (assoc :worldModelId-obj (-pull port (get rec :nvidia_cosmos.SimRun/worldModelId))))))))

(defn update-sim-run
  "Update a SimRun; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :worldModelId) (conj [:db/add id :nvidia_cosmos.SimRun/worldModelId (get data :worldModelId)]))
                   (cond-> (contains? data :prompt) (conj [:db/add id :nvidia_cosmos.SimRun/prompt (get data :prompt)]))
                   (cond-> (contains? data :frames) (conj [:db/add id :nvidia_cosmos.SimRun/frames (as-long (get data :frames))]))
                   (cond-> (contains? data :status) (conj [:db/add id :nvidia_cosmos.SimRun/status (get data :status)]))
                   (conj [:db/add id :nvidia_cosmos.SimRun/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-sim-run
  "Delete a SimRun."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Embodiment ────────────────────────────────────────────────────────────────
(defn create-embodiment
  "Create a Embodiment."
  [port data]
  (require-fields data ["name" "dof"])
  (let [id (new-id "cosmos_emb")
        e {:db/id id
           :nvidia_cosmos.Embodiment/id id
           :nvidia_cosmos.Embodiment/name (get data :name)
           :nvidia_cosmos.Embodiment/dof (as-long (get data :dof))
           :nvidia_cosmos.Embodiment/robotType (get data :robotType)
           :nvidia_cosmos.Embodiment/urdf (get data :urdf)
           :nvidia_cosmos.Embodiment/createdAt (now)
           :nvidia_cosmos.Embodiment/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-embodiments
  "List Embodiment with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-embodiments port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :nvidia_cosmos.Embodiment/id))
         rows (apply-filters rows (:filter opts) [:nvidia_cosmos.Embodiment/name :nvidia_cosmos.Embodiment/dof :nvidia_cosmos.Embodiment/robotType :nvidia_cosmos.Embodiment/urdf])]
     (paginate rows opts))))

(defn get-embodiment
  "Retrieve a Embodiment by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-embodiment port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-embodiment
  "Update a Embodiment; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :name) (conj [:db/add id :nvidia_cosmos.Embodiment/name (get data :name)]))
                   (cond-> (contains? data :dof) (conj [:db/add id :nvidia_cosmos.Embodiment/dof (as-long (get data :dof))]))
                   (cond-> (contains? data :robotType) (conj [:db/add id :nvidia_cosmos.Embodiment/robotType (get data :robotType)]))
                   (cond-> (contains? data :urdf) (conj [:db/add id :nvidia_cosmos.Embodiment/urdf (get data :urdf)]))
                   (conj [:db/add id :nvidia_cosmos.Embodiment/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-embodiment
  "Delete a Embodiment."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Prompt ────────────────────────────────────────────────────────────────
(defn create-prompt
  "Create a Prompt."
  [port data]
  (require-fields data ["text" "modality"])
  (let [id (new-id "cosmos_pro")
        e {:db/id id
           :nvidia_cosmos.Prompt/id id
           :nvidia_cosmos.Prompt/text (get data :text)
           :nvidia_cosmos.Prompt/modality (get data :modality)
           :nvidia_cosmos.Prompt/conditioning (get data :conditioning)
           :nvidia_cosmos.Prompt/createdAt (now)
           :nvidia_cosmos.Prompt/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-prompts
  "List Prompt with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-prompts port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :nvidia_cosmos.Prompt/id))
         rows (apply-filters rows (:filter opts) [:nvidia_cosmos.Prompt/text :nvidia_cosmos.Prompt/modality :nvidia_cosmos.Prompt/conditioning])]
     (paginate rows opts))))

(defn get-prompt
  "Retrieve a Prompt by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-prompt port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-prompt
  "Update a Prompt; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :text) (conj [:db/add id :nvidia_cosmos.Prompt/text (get data :text)]))
                   (cond-> (contains? data :modality) (conj [:db/add id :nvidia_cosmos.Prompt/modality (get data :modality)]))
                   (cond-> (contains? data :conditioning) (conj [:db/add id :nvidia_cosmos.Prompt/conditioning (get data :conditioning)]))
                   (conj [:db/add id :nvidia_cosmos.Prompt/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-prompt
  "Delete a Prompt."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── GuardrailCheck ────────────────────────────────────────────────────────────────
(defn create-guardrail-check
  "Create a GuardrailCheck."
  [port data]
  (require-fields data ["policy" "verdict"])
  (let [id (new-id "cosmos_gua")
        e {:db/id id
           :nvidia_cosmos.GuardrailCheck/id id
           :nvidia_cosmos.GuardrailCheck/simRunId (get data :simRunId)
           :nvidia_cosmos.GuardrailCheck/policy (get data :policy)
           :nvidia_cosmos.GuardrailCheck/verdict (get data :verdict)
           :nvidia_cosmos.GuardrailCheck/score (as-double (get data :score))
           :nvidia_cosmos.GuardrailCheck/createdAt (now)
           :nvidia_cosmos.GuardrailCheck/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-guardrail-checks
  "List GuardrailCheck with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-guardrail-checks port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :nvidia_cosmos.GuardrailCheck/id))
         rows (apply-filters rows (:filter opts) [:nvidia_cosmos.GuardrailCheck/simRunId :nvidia_cosmos.GuardrailCheck/policy :nvidia_cosmos.GuardrailCheck/verdict :nvidia_cosmos.GuardrailCheck/score])]
     (paginate rows opts))))

(defn get-guardrail-check
  "Retrieve a GuardrailCheck by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-guardrail-check port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec
         (and want (contains? want :simRunId) (get rec :nvidia_cosmos.GuardrailCheck/simRunId))
         (assoc :simRunId-obj (-pull port (get rec :nvidia_cosmos.GuardrailCheck/simRunId))))))))

(defn update-guardrail-check
  "Update a GuardrailCheck; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :simRunId) (conj [:db/add id :nvidia_cosmos.GuardrailCheck/simRunId (get data :simRunId)]))
                   (cond-> (contains? data :policy) (conj [:db/add id :nvidia_cosmos.GuardrailCheck/policy (get data :policy)]))
                   (cond-> (contains? data :verdict) (conj [:db/add id :nvidia_cosmos.GuardrailCheck/verdict (get data :verdict)]))
                   (cond-> (contains? data :score) (conj [:db/add id :nvidia_cosmos.GuardrailCheck/score (as-double (get data :score))]))
                   (conj [:db/add id :nvidia_cosmos.GuardrailCheck/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-guardrail-check
  "Delete a GuardrailCheck."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── REST surface (host wires these to the kotoba-clj gateway) ──────────────
(def routes
  [{:method "POST" :path "/v1/worldmodels" :op :create :entity "WorldModel"}
   {:method "GET" :path "/v1/worldmodels" :op :list :entity "WorldModel"}
   {:method "GET" :path "/v1/worldmodels/:id" :op :get :entity "WorldModel"}
   {:method "PATCH" :path "/v1/worldmodels/:id" :op :update :entity "WorldModel"}
   {:method "DELETE" :path "/v1/worldmodels/:id" :op :delete :entity "WorldModel"}
   {:method "POST" :path "/v1/tokenizers" :op :create :entity "Tokenizer"}
   {:method "GET" :path "/v1/tokenizers" :op :list :entity "Tokenizer"}
   {:method "GET" :path "/v1/tokenizers/:id" :op :get :entity "Tokenizer"}
   {:method "PATCH" :path "/v1/tokenizers/:id" :op :update :entity "Tokenizer"}
   {:method "DELETE" :path "/v1/tokenizers/:id" :op :delete :entity "Tokenizer"}
   {:method "POST" :path "/v1/simruns" :op :create :entity "SimRun"}
   {:method "GET" :path "/v1/simruns" :op :list :entity "SimRun"}
   {:method "GET" :path "/v1/simruns/:id" :op :get :entity "SimRun"}
   {:method "PATCH" :path "/v1/simruns/:id" :op :update :entity "SimRun"}
   {:method "DELETE" :path "/v1/simruns/:id" :op :delete :entity "SimRun"}
   {:method "POST" :path "/v1/embodiments" :op :create :entity "Embodiment"}
   {:method "GET" :path "/v1/embodiments" :op :list :entity "Embodiment"}
   {:method "GET" :path "/v1/embodiments/:id" :op :get :entity "Embodiment"}
   {:method "PATCH" :path "/v1/embodiments/:id" :op :update :entity "Embodiment"}
   {:method "DELETE" :path "/v1/embodiments/:id" :op :delete :entity "Embodiment"}
   {:method "POST" :path "/v1/prompts" :op :create :entity "Prompt"}
   {:method "GET" :path "/v1/prompts" :op :list :entity "Prompt"}
   {:method "GET" :path "/v1/prompts/:id" :op :get :entity "Prompt"}
   {:method "PATCH" :path "/v1/prompts/:id" :op :update :entity "Prompt"}
   {:method "DELETE" :path "/v1/prompts/:id" :op :delete :entity "Prompt"}
   {:method "POST" :path "/v1/guardrailchecks" :op :create :entity "GuardrailCheck"}
   {:method "GET" :path "/v1/guardrailchecks" :op :list :entity "GuardrailCheck"}
   {:method "GET" :path "/v1/guardrailchecks/:id" :op :get :entity "GuardrailCheck"}
   {:method "PATCH" :path "/v1/guardrailchecks/:id" :op :update :entity "GuardrailCheck"}
   {:method "DELETE" :path "/v1/guardrailchecks/:id" :op :delete :entity "GuardrailCheck"}])

;; collection → CRUD fns, keyed by the /v1/<collection> path segment
(def ^:private handlers
  {"worldmodels" {:create create-world-model :list list-world-models :get get-world-model :update update-world-model :delete delete-world-model}
   "tokenizers" {:create create-tokenizer :list list-tokenizers :get get-tokenizer :update update-tokenizer :delete delete-tokenizer}
   "simruns" {:create create-sim-run :list list-sim-runs :get get-sim-run :update update-sim-run :delete delete-sim-run}
   "embodiments" {:create create-embodiment :list list-embodiments :get get-embodiment :update update-embodiment :delete delete-embodiment}
   "prompts" {:create create-prompt :list list-prompts :get get-prompt :update update-prompt :delete delete-prompt}
   "guardrailchecks" {:create create-guardrail-check :list list-guardrail-checks :get get-guardrail-check :update update-guardrail-check :delete delete-guardrail-check}})

(defn- expand-opts [params]
  (when-let [x (:expand params)]
    {:expand (set (map keyword (str/split (str x) #",")))}))

(defn dispatch
  "Route an HTTP-ish request through `routes` to the CRUD fns.
   req: {:method (:get/:post/:patch/:delete) :path /v1/<coll>[/<id>] :params {} :body {}}.
   Returns {:status int :body any} — the runnable L4 service surface."
  [port {:keys [method path params body]}]
  (let [segs (->> (str/split (or path "") #"/") (remove str/blank?) vec)
        coll (get segs 1)
        id   (get segs 2)
        h    (get handlers coll)
        params (or params {})]
    (cond
      (nil? h) {:status 404 :body {:error "unknown collection"}}
      (and (= method :post) (nil? id)) {:status 201 :body ((:create h) port (or body params))}
      (and (= method :get) (nil? id)) {:status 200 :body ((:list h) port params)}
      (and (= method :get) id) (if-let [r ((:get h) port id (expand-opts params))]
                                 {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (#{:patch :put} method) id) (if-let [r ((:update h) port id (or body params))]
                                         {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (= method :delete) id) {:status 200 :body ((:delete h) port id)}
      :else {:status 405 :body {:error "method not allowed"}})))

(defn healthz []
  {:status "ok" :actor "nvidia_cosmos-compat" :tier "L4"
   :lang "clojure" :persistence "datomic-eavt-kotoba"
   :entities entities})
